name: Deploy Rendered Site

on:
  push:
    branches: [ src ]

env:
  CARGO_TERM_COLOR: always

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v2
      with:
        mdbook-version: 'latest'
    - name: Install mdbook-toc
      run: cargo install mdbook-toc
    - uses: actions/checkout@v3

    # Each deploy overwrites the contents of `main` branch from
    # `src`, but also introduces a merge structure so that the history of
    # `main` is tracked:
    - run: mdbook build
    - name: Replace Source Files with Rendered Files
      run: |
        rm -rf .github .nojekyll book.toml README.md src
        mv book/.* book/* .
        rmdir book
    - name: Disable jekyll
      run: touch .nojekyll
    - name: Commit and Push Render to main
      run: |
        set -x

        # fetch main
        git fetch origin refs/heads/main

        # Save the contents of the working dir into a tree hash:
        git add --all
        CONTENTS="$(git write-tree)"

        # Synthesize a "faked" merge commit of `src` onto `main` with the rendered contents:
        COMMIT="$(git commit-tree "$CONTENTS" -p origin/main -p src -m 'Auto-deploy: rendered output')"

        # Update `main` branch upstream:
        git push origin "$COMMIT:refs/heads/main"
